services:
  - type: web
    name: yogesh-portfolio
    runtime: java
    plan: free
    buildCommand: mvn -DskipTests clean package
    startCommand: java -jar target/*.jar
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
